name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        force_orphan: true


    # steps:
    #   - uses: actions/setup-python@v5
    #   - name: Install dependencies
    #     run: |
    #       pip install sphinx sphinx_rtd_theme myst_parser
    #   - name: Sphinx build
    #     run: |
    #       sphinx-build doc _build
    #   - name: Deploy to GitHub Pages
    #     uses: peaceiris/actions-gh-pages@v3
    #     if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    #     with:
    #       publish_branch: gh-pages
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: _build/
    #       force_orphan: true